### ISSUE TITLE
libexpat.so.1: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by meyer1994** [lambgeo/geo-layer#11]
Hi. 
This error has appearead again in this new layer. And I can reproduce it, finally.

I've cloned this repo and created a makefile with the commands described in the README. However, when trying to run a simple python function, it gives the error from the title.

Makefile:
```makefile
.PHONY: layer test

layer:
	docker build --tag package:latest . --build-arg GDAL_VERSION=3.0 --build-arg PYTHON_VERSION=3.8
	docker run --name lambda -w /var/task -itd package:latest bash
	docker cp scripts/create-lambda-layer.sh lambda:/create-lambda-layer.sh
	docker exec -it lambda bash /create-lambda-layer.sh
	docker cp lambda:/tmp/package.zip package.zip
	docker stop lambda
	docker rm lambda

test:
	unzip package.zip -d layer
	docker run \
		--rm \
		-v $(shell pwd):/var/task:ro,delegated \
		-v $(shell pwd)/layer:/opt:ro,delegated \
    	-e GDAL_DATA="/opt/share/gdal" \
    	-e PROJ_LIB="/opt/share/proj" \
		lambci/lambda:python3.8 handler.handler '{"some": "data"}'
```

Python function:
```python
import numpy
import rasterio

def handler(event, context):
    print(numpy.__version__)
    print(rasterio.__version__)
```

I've already checked the linking using `ldd` and it seems to be linked correctly. But when executing the function, it does not work.

```bash
$ docker run --rm -it lambgeo/lambda:gdal3.0-py3.8 bash -c "ldd /opt/lib/libgdal.so | grep expat"
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fb514a28000)
```

Am I missing something?

Again, thanks for your work with these layers. They help A LOT. And sorry for pestering you with my issues :stuck_out_tongue_closed_eyes:

**Comment by vincentsarago** [comment]
😭 thanks @meyer1994 and sorry for the bug, It seems we are starting from scratch again .... while I was pretty sure we copied everything from the old layer.

**Comment by vincentsarago** [comment]
@meyer1994 is this only with python 3.8 ?

**Comment by vincentsarago** [comment]
🤦 
https://github.com/lambci/docker-lambda/blob/master/python3.7/build/Dockerfile#L1

https://github.com/lambci/docker-lambda/blob/master/python3.8/build/Dockerfile#L1

both python 3.7 and python 3.8 are not based on the same image. Sadly the fix should be upstream in /docker-lambda (and it won't be an easy one 😭)

**Comment by vincentsarago** [comment]
@meyer1994 I'm going to remove any mention to python 3.8 layers for now and add them back when this will be fixed.
