### ISSUE TITLE
Using binaries cannot find libexpat.so.1

### ISSUE THREAD

**Issue by TimJMartin** [lambgeo/geo-layer#14]
Hi

I am trying to use the geo-layer with a NodeJS 10.x AWS Lambda function and calling ogr2ogr using child_process.exec however I get the following error

```
ogr2ogr: error while loading shared libraries: libexpat.so.1: cannot open shared object file: No such file or directory
```
Looking at the docker image it does seem to be built with expat so maybe I am not correctly setting the environment variables or maybe I need to set the LD_LIBRARY_PATH?

I have used the same method from a Python 3.7 AWS Lambda function using subprocess and it worked fine.

Any ideas?

Many thanks

**Comment by vincentsarago** [comment]
Hi @TimJMartin 
Saldy this is related to https://github.com/lambgeo/docker-lambda/issues/8
The new runtimes need lib compile under amazonlinux2 images :-( 

I need to update the allowed runtime for the main layer so its not working for those `new` runtime
