### ISSUE TITLE
add layer in eu-west-1

### ISSUE THREAD

**Issue by vincentsarago** [lambgeo/geo-layer#15]

**Comment by vincentsarago** [comment]
done manually for gdal24-py37

**Comment by adrianmelero** [comment]
Hi @vincentsarago Still having error:
is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:524387336408:layer:gdal24-py37-geolayer:1 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: f4ca5d96-081f-41fb-9917-9eb8aacad689)

**Comment by vincentsarago** [comment]
Can you try again @adrianmelero ?

**Comment by adrianmelero** [comment]
Great!! Its working!!! Thanks @vincentsarago
