### ISSUE TITLE
Unable to import module 'lambda_function': No module named 'osgeo'

### ISSUE THREAD

**Issue by bledem** [lambgeo/geo-layer#22]
I added a new layer with following ARN: arn:aws:lambda:ap-northeast-1:524387336408:layer:gdal24-python37-geo:2
Even if the python code finds libraries like shapely, it does not find osgeo so gdal. Could you help me please?

**Comment by vincentsarago** [comment]
`gdal` python wrapper are not part of the geo-layer modules

please see https://github.com/lambgeo/geo-layer#2-advanced-need-other-python-dependencies on how to create your own package.

**Comment by christiangilaquino** [comment]
> `gdal` python wrapper are not part of the geo-layer modules
> 
> please see https://github.com/lambgeo/geo-layer#2-advanced-need-other-python-dependencies on how to create your own package.

Do you have public arn for python 3.7 in a tokyo server?

**Comment by vincentsarago** [comment]
@christiangilaquino full list of region is https://github.com/lambgeo/geo-layer#regions
